### --- DOTF ZSH ENV --- ###

export EDITOR="nvim"

export READER="zathura"
export VISUAL=$EDITOR
export CODEEDITOR=$EDITOR
export TERMINAL="urxvt" # move to alacritty
export BROWSER="chromium"
export OPENER="xdg-open"
export WALLPAPER="$HOME/keanu/wallpapers/default.jpg"


### Python ###
export PATH=$PATH:$HOME/.local/bin


### Go ###
export GOPATH=/home/alexjperkins/go
export GOBIN=/home/alexjperkins/go/bin
export PATH=$PATH:$GOBIN


### Rust ###
export PATH=$PATH:$HOME/.cargo/bin


### LESS TERMCAP ###
export LESS_TERMCAP_mb=$(tput bold; tput setaf 4)  ## blue
export LESS_TERMCAP_md=$(tput bold; tput setaf 5)  ## magenta
export LESS_TERMCAP_so=$(tput bold; tput setaf 3)  ## yellow
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 6)  ## cyan
export LESS_TERMCAP_me=$(tput sgr0)  ## End bold, blinking, standout & underline


### Misc ###
export DOTF_REPOS="$HOME/repos"
export DOTF_WIKI="$DOTF_REPOS/wiki"
export DOTF_FINANCES="$HOME/repos/wiki/personal/finances.md"	
export DOTF_TIMETABLE="$HOME/repos/wiki/personal/timetable.md"	
export DOTF_GOALS="$HOME/repos/wiki/personal/goals.md"	
export TODOPATH="$HOME/repos/wiki/personal/todo.md"
export TOLEARNPATH="$HOME/repos/wiki/personal/tolearn.md"
export TOREADPATH="$HOME/repos/wiki/personal/toread.md"

export WIKIPATH="$HOME/repos/wiki/"
export VERVPATH="$HOME/verv/"
