### --- DOTF ZSH ENV --- ###

# MacOS
if [[ "$IS_MACOS" == "1" ]]; then
	export LSCOLORS="fxgxhxdacxDaDaxbadacex"
	export CLICOLOR=1
	export TERMINAL="alacritty" # move to alacritty
	export BROWSER="chrome"
else
	export OPENER="xdg-open"
	export TERMINAL="urxvt" # move to alacritty
	export READER="zathura"
	export WALLPAPER="$HOME/keanu/wallpapers/default.jpg"
	export BROWSER="chromium"
fi

export EDITOR="nvim"
export VISUAL=$EDITOR
export CODEEDITOR=$EDITOR
export XDG_CONFIG_HOME=$HOME/.config


### Dotf ###
export DOTF_PATH=$HOME/dotf


### Python ###
export PATH=$PATH:$HOME/.local/bin


### Go ###
export GOPATH=$HOME
export GOBIN=$HOME/bin
export PATH=$PATH:$GOBIN


### Rust ###
export PATH=$PATH:$HOME/.cargo/bin


### LESS TERMCAP ###
export LESS_TERMCAP_mb=$(tput bold; tput setaf 4)  ## blue
export LESS_TERMCAP_md=$(tput bold; tput setaf 5)  ## magenta
export LESS_TERMCAP_so=$(tput bold; tput setaf 3)  ## yellow
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 6)  ## cyan
export LESS_TERMCAP_me=$(tput sgr0)  ## End bold, blinking, standout & underline


### Misc ###
export DOTF_REPOS="$HOME/repos"
export DOTF_WIKI="$DOTF_REPOS/wiki"
export WIKIPATH="$HOME/repos/wiki/"
export DOTF_FINANCES="$HOME/repos/wiki/personal/finances.md"	
export DOTF_TIMETABLE="$HOME/repos/wiki/personal/timetable.md"	
export DOTF_GOALS="$HOME/repos/wiki/personal/goals.md"	
export TODOPATH="$HOME/repos/wiki/personal/todo.md"
export TOLEARNPATH="$HOME/repos/wiki/personal/tolearn.md"
export TOREADPATH="$HOME/repos/wiki/personal/toread.md"
