### --- Keanu ZSH ENV --- ###

export EDITOR="nvim"

export READER="zathura"
export VISUAL=$EDITOR
export CODEEDITOR=$EDITOR
export TERMINAL="urxvt"
export BROWSER="chromium"
export VIMBROWSER="firefox"
export OPENER="xdg-open"
export WM="i3"
export WALLPAPER="$(echo $HOME/keanu/wallpapers/default.jpg)"


### Python ###
export PATH=$PATH:$HOME/.local/bin


### Go ###
export GOPATH=/home/alexjperkins/go
export GOBIN=/home/alexjperkins/go/bin
export PATH=$PATH:$GOBIN


### Rust ###
export PATH=$PATH:$HOME/.cargo/bin


### LESS TERMCAP ###
export LESS_TERMCAP_mb=$(tput bold; tput setaf 4)  ## blue
export LESS_TERMCAP_md=$(tput bold; tput setaf 5)  ## magenta
export LESS_TERMCAP_so=$(tput bold; tput setaf 3)  ## yellow
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 6)  ## cyan
export LESS_TERMCAP_me=$(tput sgr0)  ## End bold, blinking, standout & underline


### Misc ###
export KEANU_REPOS="$HOME/repos"
export KEANU_WIKI="$KEANU_REPOS/wiki"
export KEANU_FINANCES="$HOME/repos/wiki/personal/finances.md"	
export KEANU_TIMETABLE="$HOME/repos/wiki/personal/timetable.md"	
export KEANU_GOALS="$HOME/repos/wiki/personal/goals.md"	
export TODOPATH="$HOME/repos/wiki/personal/todo.md"
export TOLEARNPATH="$HOME/repos/wiki/personal/tolearn.md"
export TOREADPATH="$HOME/repos/wiki/personal/toread.md"

export WIKIPATH="$HOME/repos/wiki/"
export VERVPATH="$HOME/verv/"


### Kraken Pi ###
export KPCIP=192.168.1.255/24
export KCDURL="http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/"
